[platformio]
src_dir = firmware/arcadeos

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/DHT sensor library@1.4.6
  adafruit/Adafruit Unified Sensor@1.1.15
  knolleary/PubSubClient@2.8
build_flags =
  -D CORE_DEBUG_LEVEL=0
